# Generated by Django 3.2 on 2021-04-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210427_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_address',
            field=models.CharField(max_length=40),
        ),
    ]
