# Generated by Django 3.2 on 2021-06-16 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[ ]*[A-Za-z0-9][A-Za-z0-9 ]*$', 'Only letters and numbers allowed.')]),
        ),
    ]
