# Generated by Django 3.2 on 2021-05-08 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('event_time', models.TimeField()),
                ('event_price', models.CharField(max_length=50, null=True)),
                ('event_contact', models.CharField(max_length=100, null=True)),
                ('event_category', models.CharField(choices=[('fitness', 'fitness'), ('services', 'services'), ('kids', 'kids'), ('business', 'business'), ('other', 'other')], default='fitness', max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
