# Generated by Django 3.2 on 2021-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
