# Generated by Django 3.2 on 2021-05-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Arts', 'arts'), ('Food & Drinks', 'food-and-drinks'), ('Fitness & Sports', 'fitness-and-sports'), ('Kids', 'kids'), ('Services', 'services'), ('Other', 'other')], default='Arts', max_length=100),
        ),
    ]
