# Generated by Django 3.2 on 2021-05-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Food & Drinks', 'Food & Drinks'), ('Fitness & Sports', 'Fitness & Sports'), ('Kids', 'Kids'), ('Services', 'Services'), ('Other', 'Other')], default='Arts', max_length=100),
        ),
    ]
