# Generated by Django 3.2 on 2021-06-01 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_contact',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[ ]*[A-Za-z0-9][A-Za-z0-9 ]*$', 'Only letters and numbers allowed.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator('^[ ]*[A-Za-z0-9][A-Za-z0-9 ]*$', 'Only letters and numbers allowed.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_price',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[ ]*[A-Za-z0-9][A-Za-z0-9 ]*$', 'Only letters and numbers allowed.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[ ]*[A-Za-z0-9][A-Za-z0-9 ]*$', 'Only letters and numbers allowed.')]),
        ),
    ]
