# Generated by Django 3.2 on 2021-06-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210601_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
