# Generated by Django 3.2 on 2021-06-01 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'Only letters and numbers allowed.')]),
        ),
    ]
