# Generated by Django 3.2 on 2021-06-16 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210601_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('^[ ]*[A-Za-z0-9][A-Za-z0-9 ]*$', 'Only letters and numbers allowed.')]),
        ),
    ]
